version: '3.3'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-prod
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file
      - ./vault-config:/vault/config
    command: vault server -config=/vault/config/vault.hcl

volumes:
  vault_data:
